### ISSUE TITLE
Multi line cell value is flattened

### ISSUE THREAD

**Issue by tewald** [pyexcel/pyexcel-ods#5]
Hi,

I'm trying to read a multi line cell value, but I'm getting a single line string.
What I'm getting:

single line | multi line
------------- | -----------------------
correct|thisshouldbemultiline

What should be:

single line | multi line
------------- | -----------------------
correct     | this<br>should<br>be<br>multi<br>line

Saving in xls format and using pyexcel-xls works, but I need to support ods files too.

Thanks!

**Comment by chfw** [comment]
Could you please try if it does the job for you? 

    pip install https://github.com/pyexcel/pyexcel-ods/archive/master.zip

Meanwhile, to all pyexcel users:

No promise was given that new feature request will be implemented assp. This feature happens to be very trivial to implement and I happen to have some slack time. That's why it is done promptly. Please do not take this case against me later on :)

**Comment by tewald** [comment]
Hi!
It works!
I'm getting 2 extra empty rows, but the cell contents of the multi line texts are OK.
From my part, I didn't expected a fix asap, but I'm very happy that you take the time to do it.
Will try do contribute with patches in the future. :-)

**Comment by chfw** [comment]
Thanks for the quick feedback. I will include it in the next release-> 0.1.1

**Comment by chfw** [comment]
released this feature in 0.1.1 in pypi
